name: build unstable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # All history
        fetch-depth: 0

    - name: Fetch tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: go test -v  ./...

    - name: Build OPKG package for Turris Omnia
      run: make opkg-omnia

    - name: Extract version number
      run: |
        version="$(ls build/ipkbuild/lightkeeper-*.ipk | sed -E 's/.*lightkeeper-(.*)\.ipk/\1/')"
        echo "::set-output name=version::$version"
      id: version

    - if: github.event_name != 'release'
      name: Upload to Unstable Bintray Repo
      uses: hpcsc/upload-bintray-docker-action@v1
      with:
        repository: lightkeeper-unstable
        package: lightkeeper
        version: ${{steps.version.outputs.version}}
        sourcePath: build/ipkbuild/lightkeeper-*.ipk
        username: ${{secrets.BINTRAY_USERNAME}}
        apiKey: ${{secrets.BINTRAY_API_KEY}}

    - if: github.event_name == 'release'
      name: Upload to Stable Bintray Repo
      uses: hpcsc/upload-bintray-docker-action@v1
      with:
        repository: ightkeeper
        package: lightkeeper
        version: ${{steps.version.outputs.version}}
        sourcePath: build/ipkbuild/lightkeeper-*.ipk
        username: ${{secrets.BINTRAY_USERNAME}}
        apiKey: ${{secrets.BINTRAY_API_KEY}}

